#!/bin/bash
# Platform analytic local testing script.
#
# Usage:
#   test-platform -h
#
# Copyright 2017-2019, Voxel51, Inc.
# voxel51.com
#

TESTS_DIR=$(python -c "import voxel51.platform.constants as voxc; print(voxc.TESTS_DIR)")
PLATFORM_TESTS_DIR="${TESTS_DIR}/platform"

node "${PLATFORM_TESTS_DIR}/server/index.js" "$@"
