#!/bin/bash
# Platform analytic local testing script.
#
# Usage:
#   test-platform -h
#
# Copyright 2017-2019, Voxel51, Inc.
# voxel51.com
#

PLATFORM_TESTS_DIR="$(dirname "$0")"

node "${PLATFORM_TESTS_DIR}/server/index.js" "$@"
